name: Python Setup
description: Installs Python and necessary dependencies
inputs:
  working-directory:
    description: 'The path to the workspace'
    required: false
    default: ${{ github.workspace }}

runs:
  using: composite
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
      working-directory: ${{ inputs.working-directory }}
