# Workflow to check if a user is a member of the org

name: Check Is Bot

on:
  workflow_call:
    outputs:
      is_bot:
        value: ${{ jobs.check-is-bot.outputs.is_bot }}

jobs:
  check-is-bot:
    name: Check Is Bot
    runs-on: ubuntu-latest
    # Dont run this workflow on merge queue
    if:  ${{ github.event_name != 'merge_group' }}
    outputs:
      is_member: ${{ steps.check-is-bot.outputs.is_bot}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'dfinity/public-workflows'

      - name: Python Setup
        uses: ./.github/workflows/python-setup

      - name: Check Is Bot
        id:  check-is-bot
        run: |
          export PYTHONPATH="$PWD/reusable_workflows/"
          python reusable_workflows/repo_policies/check_is_bot.py
        shell: bash
        env:
          USER: ${{ github.event.pull_request.user.login }}
