name: Repository Policies

on:
  workflow_call:

jobs:
  check-is-bot:
    uses: dfinity/public-workflows/.github/workflows/checl_is_bot.yml@main
    secrets: inherit

  check-bot-policies:
    name: Check Bot Policies
    runs-on: ubuntu-latest
    needs: check-is-bot
    if: ${{ needs.check-is-bot.outputs.is_member != 'true' && needs.check-is-bot.result == 'success' }}
    steps:
        # First check out code from public-workflows
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: dfinity/public-workflows
          path: public-workflows

        # Then switch back to this repository to make sure it's run from current
      - name: Checkout Original Repository
        uses: actions/checkout@v4
        with:
          path: current-repo # need to specify another path to avoid overwriting the first checkout
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 100

      - name: Bot Checks
        id:  bot-checks
        run: |
          set -euo pipefail
          export PYTHONPATH="$PWD/public-workflows/reusable_workflows/"
          python public-workflows/reusable_workflows/repo_policies/check_bot_approved_files.py
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # no actual token stored, read-only permissions
          GH_ORG: ${{ github.repository_owner }}
          USER: ${{ github.event.pull_request.user.login }}
          REPO: ${{ github.event.repository.name }}
          MERGE_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          BRANCH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          REPO_PATH: current-repo
