# triggered on all repositories via rulesets

name: Repo Policies Ruleset

on:
  pull_request:
  merge_group:

jobs:
  call-repo-policies:
    uses: dfinity/public-workflows/.github/workflows/repo_policies.yml@main
    secrets: inherit
