# triggered on all repositories via rulesets

name: Org Repo Policy Check

on:
  pull_request_target:
  merge_group:

jobs:
  call-repo-policies:
    uses: dfinity/public-workflows/.github/workflows/repo_policies.yml@main
    secrets: inherit
