on:
  pull_request:

jobs:
  test-multiple-checkouts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CLA
        uses: actions/checkout@v4
        with:
          repository: dfinity/cla
          path: cla

      - name: Debug
        shell: bash
        run: ls -la

      - name: Checkout Original Repository
        uses: actions/checkout@v4
        with:
          path: public-workflows

      - name: Debug
        shell: bash
        run: |
          ls -la cla
          ls -la public-workflows
