name: Test Workflow

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 256

      - name: Python Setup
        uses: ./.github/workflows/python-setup
        
      - name: Security Checks
        id:  security-checks
        run: python reusable_workflows/security_checks/security_checks.py
        continue-on-error: true
        shell: bash
        env:
          MERGE_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          BRANCH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          REPO: ${{ github.event.repository.name }}

      - name: Close Pull Request
        id: close_pr
        if: ${{ steps.security-checks.outputs.security-checks != 'false' }}
        uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            Thank you for contributing! Unfortunately you have made changes to a file that is not allowed.

            Please revise your changes and reopen the pull request. Thank you for your understanding!
