name: Test Workflow

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 256

      - name: Python Setup
        uses: ./.github/workflows/python-setup
        
      - name: Check Membership
        id:  check-membership
        run: python reusable_workflows/security_checks/security_checks.py
        shell: bash
        env:
          MERGE_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          BRANCH_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          REPO: ${{ github.event.repository.name }}
